---
title: "Untitled"
output: html_document
date: '2024-06-27'
---

# Packages

```{r package, warning=FALSE, echo=TRUE}
set.seed(2024)
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tidyr) 
  library(here)
  library(ggplot2)
  library(ggpubr)
  library(metafor)
  library(metaSEM)
  library(TOSTER)
  library(raincloudplots)
  library(OpenMx)
  library(cowplot)
  library(patchwork)
  library(RoBMA)}
  )
```


# Fig. 2

```{r}

#*************************************************#
#*--------------------economics-------------------#
#*************************************************#

# individual vs. meta-analytic
# prepare data
dat_long <- data.frame(Approach = c(rep("Individual level effect size", nrow(dat_eco)), rep("Adjusted meta-analytic effect", nrow(df_eco))),
                  Estimate = c(dat_eco$mu_obs, df_eco$mu_adj))

# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Individual level effect size", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_eco <- ggdensity(dat_long, x = "Estimate",
   add = "none", rug = TRUE, alpha = 0.4,
   color = "Approach", fill = "Approach",
   palette = c("#5867AF", "#F1AEA7")) + #c("#8CA5EA", "#E3738B"))
  labs(title = "Economics", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
        ) + 
  xlim(-3,3)


# unadjusted vs. adjusted
# prepare data
dat <- select(df_eco, id, mu_unadj, mu_adj, folded_mu_adj)
dat_long <- dat %>%
  pivot_longer(cols = c(mu_unadj, mu_adj), 
               names_to = "Approach", 
               values_to = "Estimate") %>%
  mutate(Approach = dplyr::recode(Approach, 
                       mu_unadj = "Unadjusted meta-analytic effect", 
                       mu_adj = "Adjusted meta-analytic effect"))
# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Unadjusted meta-analytic effect", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_eco2 <- ggdensity(dat_long, x = "Estimate",
   add = "none", rug = TRUE, alpha = 0.4,
   color = "Approach", fill = "Approach",
   palette = c("#FCB462", "#7BC4C5")) +  # c("#FCB462", "#7BC4C5")
  labs(title = "Economics", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
        )



#*************************************************#
#*--------------------environment-------------------#
#*************************************************#
# individual vs. meta-analytic
# prepare data
dat_long <- data.frame(Approach = c(rep("Individual level effect size", nrow(dat_env)), rep("Adjusted meta-analytic effect", nrow(df_env))),
                       Estimate = c(dat_env$mu_obs, df_env$mu_adj))

# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Individual level effect size", "Adjusted meta-analytic effect"))

p.den_env <- ggdensity(dat_long, x = "Estimate",
                       add = "none", rug = TRUE, alpha = 0.4,
                       color = "Approach", fill = "Approach",
                       palette = c("#5867AF", "#F1AEA7")) + #c("#8CA5EA", "#E3738B"))
  labs(title = "Environmental Science", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  ) + 
  xlim(-3,3)


# unadjusted vs. adjusted
# prepare data
dat <- select(df_env, id, mu_unadj, mu_adj, folded_mu_adj)
dat_long <- dat %>%
  pivot_longer(cols = c(mu_unadj, mu_adj), 
               names_to = "Approach", 
               values_to = "Estimate") %>%
  mutate(Approach = dplyr::recode(Approach, 
                                  mu_unadj = "Unadjusted meta-analytic effect", 
                                  mu_adj = "Adjusted meta-analytic effect"))
# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Unadjusted meta-analytic effect", "Adjusted meta-analytic effect"))

p.den_env2 <- ggdensity(dat_long, x = "Estimate",
                        add = "none", rug = TRUE, alpha = 0.4,
                        color = "Approach", fill = "Approach",
                        palette = c("#FCB462", "#7BC4C5")) +  # c("#FCB462", "#7BC4C5")
  labs(title = "Environmental Science", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  ) +
  xlim(-2,2)


#*************************************************#
#*--------------------psychology-------------------#
#*************************************************#
# individual vs. meta-analytic
# prepare data
dat_long <- data.frame(Approach = c(rep("Individual level effect size", nrow(dat_psy)), rep("Adjusted meta-analytic effect", nrow(df_psy))),
                       Estimate = c(dat_psy$mu_obs, df_psy$mu_adj))

# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Individual level effect size", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_psy <- ggdensity(dat_long, x = "Estimate",
                       add = "none", rug = TRUE, alpha = 0.4,
                       color = "Approach", fill = "Approach",
                       palette = c("#5867AF", "#F1AEA7")) + #c("#8CA5EA", "#E3738B"))
  labs(title = "Psychology", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  ) + 
  xlim(-3,3)


# unadjusted vs. adjusted
# prepare data
dat <- select(df_psy, id, mu_unadj, mu_adj, folded_mu_adj)
dat_long <- dat %>%
  pivot_longer(cols = c(mu_unadj, mu_adj), 
               names_to = "Approach", 
               values_to = "Estimate") %>%
  mutate(Approach = dplyr::recode(Approach, 
                                  mu_unadj = "Unadjusted meta-analytic effect", 
                                  mu_adj = "Adjusted meta-analytic effect"))
# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Unadjusted meta-analytic effect", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_psy2 <- ggdensity(dat_long, x = "Estimate",
                        add = "none", rug = TRUE, alpha = 0.4,
                        color = "Approach", fill = "Approach",
                        palette = c("#FCB462", "#7BC4C5")) +  # c("#FCB462", "#7BC4C5")
  labs(title = "Psychology", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  )


#*************************************************#
#*--------------------medicine-------------------#
#*************************************************#

# individual vs. meta-analytic
# prepare data
dat_long <- data.frame(Approach = c(rep("Individual level effect size", nrow(dat_med)), rep("Adjusted meta-analytic effect", nrow(df_med))),
                       Estimate = c(dat_med$mu_obs, df_med$mu_adj))

# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Individual level effect size", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_med <- ggdensity(dat_long, x = "Estimate",
                       add = "none", rug = TRUE, alpha = 0.4,
                       color = "Approach", fill = "Approach",
                       palette = c("#5867AF", "#F1AEA7")) + #c("#8CA5EA", "#E3738B"))
  labs(title = "Medicine", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  ) + 
  xlim(-2,2)


# unadjusted vs. adjusted
# prepare data
dat <- select(df_med, id, mu_unadj, mu_adj, folded_mu_adj)
dat_long <- dat %>%
  pivot_longer(cols = c(mu_unadj, mu_adj), 
               names_to = "Approach", 
               values_to = "Estimate") %>%
  mutate(Approach = dplyr::recode(Approach, 
                                  mu_unadj = "Unadjusted meta-analytic effect", 
                                  mu_adj = "Adjusted meta-analytic effect"))
# plot
dat_long$Approach <- as.factor(dat_long$Approach)
dat_long$Approach <- factor(dat_long$Approach, levels = c("Unadjusted meta-analytic effect", "Adjusted meta-analytic effect"))

# https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html
p.den_med2 <- ggdensity(dat_long, x = "Estimate",
                        add = "none", rug = TRUE, alpha = 0.4,
                        color = "Approach", fill = "Approach",
                        palette = c("#FCB462", "#7BC4C5")) +  # c("#FCB462", "#7BC4C5")
  labs(title = "Medicine", x = "Effect size", y = "Density", fill = "", color = "") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 14),
        plot.title = element_text(hjust = 0.5),
        legend.text=element_text(size = 14)
  ) +
  xlim(-2,1)


png(filename = "fig 2.png", width = 10, height = 16, units = "in", type = "windows", res = 400)
  p.den_med + p.den_med2 +
  p.den_eco + p.den_eco2 +
  p.den_env + p.den_env2 +
  p.den_psy + p.den_psy2 +
plot_layout(ncol = 2, nrow = 4, tag_level = 'new', guides = "collect") +
plot_annotation(tag_levels = list(c('A', "B", 'C', "D", 'E', "F", 'G', "H"))) & theme(plot.tag = element_text(size = 15, face = "bold"), legend.position = "bottom") 

dev.off()

```


# Fig. 3

```{r}
# dataframe
df1 <- data.frame(Field = rep("Economics", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_eco$mu_obs), probs = 0.25),
                        quantile(abs(df_eco$mu_unadj), probs = 0.25),
                        quantile(abs(df_eco$mu_adj), probs = 0.25),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_eco$mu_obs), probs = 0.50),
                        quantile(abs(df_eco$mu_unadj), probs = 0.50),
                        quantile(abs(df_eco$mu_adj), probs = 0.50),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_eco$mu_obs), probs = 0.75),
                        quantile(abs(df_eco$mu_unadj), probs = 0.75),
                        quantile(abs(df_eco$mu_adj), probs = 0.75),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.75)))

df2 <- data.frame(Field = rep("Environmental Sciences", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_env$mu_obs), probs = 0.25),
                        quantile(abs(df_env$mu_unadj), probs = 0.25),
                        quantile(abs(df_env$mu_adj), probs = 0.25),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_env$mu_obs), probs = 0.50),
                        quantile(abs(df_env$mu_unadj), probs = 0.50),
                        quantile(abs(df_env$mu_adj), probs = 0.50),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_env$mu_obs), probs = 0.75),
                        quantile(abs(df_env$mu_unadj), probs = 0.75),
                        quantile(abs(df_env$mu_adj), probs = 0.75),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.75)))

df3 <- data.frame(Field = rep("Medicine", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_med$mu_obs), probs = 0.25),
                        quantile(abs(df_med$mu_unadj), probs = 0.25),
                        quantile(abs(df_med$mu_adj), probs = 0.25),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_med$mu_obs), probs = 0.50),
                        quantile(abs(df_med$mu_unadj), probs = 0.50),
                        quantile(abs(df_med$mu_adj), probs = 0.50),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_med$mu_obs), probs = 0.75),
                        quantile(abs(df_med$mu_unadj), probs = 0.75),
                        quantile(abs(df_med$mu_adj), probs = 0.75),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.75)))

df4 <- data.frame(Field = rep("Psychology", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_psy$mu_obs), probs = 0.25),
                        quantile(abs(df_psy$mu_unadj), probs = 0.25),
                        quantile(abs(df_psy$mu_adj), probs = 0.25),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_psy$mu_obs), probs = 0.50),
                        quantile(abs(df_psy$mu_unadj), probs = 0.50),
                        quantile(abs(df_psy$mu_adj), probs = 0.50),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_psy$mu_obs), probs = 0.75),
                        quantile(abs(df_psy$mu_unadj), probs = 0.75),
                        quantile(abs(df_psy$mu_adj), probs = 0.75),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.75)))

df <- rbind(df1, df2, df3, df4)
df$Field <- as.factor(df$Field)
df$Field <- factor(df$Field, levels = c("Medicine", "Economics", "Environmental Sciences", "Psychology"))
df$Approach <- as.factor(df$Approach)
df$Approach <- factor(df$Approach, levels = c("Adjusted and folded meta-analytic effect", "Adjusted meta-analytic effect", "Unadjusted meta-analytic effect", "Individual level effect size"))

# plot
## define colours for dots and bars
dotCOLS = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")
barCOLS = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")

p <- ggplot(df, aes(x = Approach, y = Q2, ymin = Q1, ymax = Q3, col = Field, fill = Field)) + 
  geom_linerange(linewidth = 8) +
  coord_flip() +
  geom_hline(yintercept = 0.2, lty = "longdash", color = "grey40") +
  geom_hline(yintercept = 0.5, lty = "longdash", color = "grey40") +
  geom_hline(yintercept = 0.8, lty = "longdash", color = "grey40") +
  geom_point(size=6, shape=21, colour="white", stroke = 2) +
  scale_fill_manual(values=barCOLS) +
  scale_color_manual(values=dotCOLS) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.5, 0.8, 1, 1.5), labels = c(0, 0.1, 0.2, 0.5, 0.8, 1, 1.5), expand = c(0, 0.05)) +
  theme_bw() +
  guides(fill = "none", color = "none") +
  labs(x = "", y = bquote(paste("Effect size benchmark"~"(", italic(d), ~ "family", ")")) ) +
  
  theme(axis.title = element_text(size = 18, color = "black"),
        axis.text.x = element_text(size = 18, color = "black"),
        axis.text.y = element_text(size = 16, color = "black"),
        strip.text = element_text(size = 18, color = "black"),
        plot.margin=unit(c(0,0.8,0.1,-0.5), 'cm')) +
  ggforce::facet_col(
    facets = ~Field,
    scales = "free_y",
    space = "free",
    strip.position = "top")

png(filename = "fig 3.png", width = 12, height = 12, units = "in", type = "windows", res = 400)
p
dev.off() 

#cowplot::plot_grid(p, labels = c(' '), label_size = 16, nrow = 4, ncol = 1)

# plot_layout(tag_level = 'new') +  plot_annotation(tag_levels = list(c(''))) & theme(plot.tag = element_text(size = 16, face = "bold"))  
```


# Fig. 4

https://github.com/jorvlan/raincloudplots

```{r}
# economic
df_1x1 <- data_1x1(
  array_1 = df_eco$folded_mu_adj,
  array_2 = df_eco$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p1 <- raincloud_1x1_repmes(
  data = df_1x1, # BottleRocket2
  colors = c("#009E73","#CC79A7"), # brewer.pal(n = 8, name = "Dark2")[1:2], #wes_palette("Rushmore1", 4, type = "discrete")[c(4,3,4,3)],
  fills = c("#009E73","#CC79A7"), # wes_palette("Rushmore1", 4, type = "discrete")[c(4,3,4,3)], # https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes") 
                   #limits=c(0, 100)
                   ) +
  labs(title = "Economics", x = " ", y = "Effect size") + 
  #annotate(geom = "text", x= 1, y = -1, label = "Publication bias") +
  #annotate(geom = "text", x= 4, y = -1, label = "No publication bias") +
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# environment
df_1x1 <- data_1x1(
  array_1 = df_env$folded_mu_adj,
  array_2 = df_env$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p2 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Environment", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# medicine
df_1x1 <- data_1x1(
  array_1 = df_med$folded_mu_adj,
  array_2 = df_med$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p3 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Medicine", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# medicine
df_1x1 <- data_1x1(
  array_1 = df_psy$folded_mu_adj,
  array_2 = df_psy$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p4 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Psychology", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

png(filename = "fig 3.png", width = 6, height = 15, units = "in", type = "windows", res = 600)
cowplot::plot_grid(p1, p2, p4, p4, labels = c('A', 'B', 'C', 'D'), label_size = 16, nrow = 4, ncol = 1)
dev.off()

```

