---
title: "Untitled"
output: html_document
date: '2024-06-27'
---

# Packages

```{r package, warning=FALSE, echo=TRUE}
set.seed(2024)
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tidyr) 
  library(here)
  library(ggplot2)
  library(ggpubr)
  library(metafor)
  library(metaSEM)
  library(TOSTER)
  library(raincloudplots)
  library(cowplot)
  library(patchwork)
  library(RoBMA)}
  )
```

# Function

Function calculating mean and variance based on folded distribution

```{r fun}
## folded mean
folded_es <-function(mean, variance){   
  mu <- mean
  sigma <- sqrt(variance)
  fold_mu <- sigma*sqrt(2/pi)*exp((-mu^2)/(2*sigma^2)) + mu*(1 - 2*pnorm(-mu/sigma))
  fold_mu
}

## folded variance
folded_var <- function(mean, variance){
  mu <- mean
  sigma <- sqrt(variance)
  fold_mu <- sigma*sqrt(2/pi)*exp((-mu^2)/(2*sigma^2)) + mu*(1 - 2*pnorm(-mu/sigma))
  fold_se <- sqrt(mu^2 + sigma^2 - fold_mu^2)
  # variance
  fold_v <- fold_se^2
  fold_v
}


# alternatively
foldnorm <-  function(mu, var){
	   sd <- sqrt(var)
     postfnorm <- stats::dnorm(mu, 0, sd)*2*sd^2 + mu*(2*stats::pnorm(mu, 0, sd) -1)
		    est <- postfnorm
		    var.fnorm <- mu^2 + sd^2 - (sd*sqrt(2/pi)*exp((-1*mu^2)/(2*sd^2)) + mu*(1-2*stats::pnorm(-1*mu/sd, 0, 1)))^2
		    est <- data.frame(Mean=est, Variance = var.fnorm)
}
```

# Figure 2

```{r}
# dataframe
df1 <- data.frame(Field = rep("Economics", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_eco$mu_obs), probs = 0.25),
                        quantile(abs(df_eco$mu_unadj), probs = 0.25),
                        quantile(abs(df_eco$mu_adj), probs = 0.25),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_eco$mu_obs), probs = 0.50),
                        quantile(abs(df_eco$mu_unadj), probs = 0.50),
                        quantile(abs(df_eco$mu_adj), probs = 0.50),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_eco$mu_obs), probs = 0.75),
                        quantile(abs(df_eco$mu_unadj), probs = 0.75),
                        quantile(abs(df_eco$mu_adj), probs = 0.75),
                        quantile(abs(df_eco$folded_mu_adj), probs = 0.75)))

df2 <- data.frame(Field = rep("Environment", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_env$mu_obs), probs = 0.25),
                        quantile(abs(df_env$mu_unadj), probs = 0.25),
                        quantile(abs(df_env$mu_adj), probs = 0.25),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_env$mu_obs), probs = 0.50),
                        quantile(abs(df_env$mu_unadj), probs = 0.50),
                        quantile(abs(df_env$mu_adj), probs = 0.50),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_env$mu_obs), probs = 0.75),
                        quantile(abs(df_env$mu_unadj), probs = 0.75),
                        quantile(abs(df_env$mu_adj), probs = 0.75),
                        quantile(abs(df_env$folded_mu_adj), probs = 0.75)))

df3 <- data.frame(Field = rep("Medicine", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_med$mu_obs), probs = 0.25),
                        quantile(abs(df_med$mu_unadj), probs = 0.25),
                        quantile(abs(df_med$mu_adj), probs = 0.25),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_med$mu_obs), probs = 0.50),
                        quantile(abs(df_med$mu_unadj), probs = 0.50),
                        quantile(abs(df_med$mu_adj), probs = 0.50),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_med$mu_obs), probs = 0.75),
                        quantile(abs(df_med$mu_unadj), probs = 0.75),
                        quantile(abs(df_med$mu_adj), probs = 0.75),
                        quantile(abs(df_med$folded_mu_adj), probs = 0.75)))

df4 <- data.frame(Field = rep("Psychology", 4),
                 Approach = c("Individual level effect size", "Unadjusted meta-analytic effect", "Adjusted meta-analytic effect", "Adjusted and folded meta-analytic effect"),
                 Q1 = c(quantile(abs(dat_psy$mu_obs), probs = 0.25),
                        quantile(abs(df_psy$mu_unadj), probs = 0.25),
                        quantile(abs(df_psy$mu_adj), probs = 0.25),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.25)),
                 Q2 = c(quantile(abs(dat_psy$mu_obs), probs = 0.50),
                        quantile(abs(df_psy$mu_unadj), probs = 0.50),
                        quantile(abs(df_psy$mu_adj), probs = 0.50),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.50)),
                 Q3 = c(quantile(abs(dat_psy$mu_obs), probs = 0.75),
                        quantile(abs(df_psy$mu_unadj), probs = 0.75),
                        quantile(abs(df_psy$mu_adj), probs = 0.75),
                        quantile(abs(df_psy$folded_mu_adj), probs = 0.75)))

df <- rbind(df1, df2, df3, df4)
df$Field <- as.factor(df$Field)
df$Field <- factor(df$Field, levels = c("Medicine", "Environment", "Economics", "Psychology"))
df$Approach <- as.factor(df$Approach)
df$Approach <- factor(df$Approach, levels = c("Adjusted and folded meta-analytic effect", "Adjusted meta-analytic effect", "Unadjusted meta-analytic effect", "Individual level effect size"))

# plot
## define colours for dots and bars
dotCOLS = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")
barCOLS = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A")

p <- ggplot(df, aes(x = Approach, y = Q2, ymin = Q1, ymax = Q3, col = Field, fill = Field)) + 
  geom_linerange(linewidth = 8) +
  coord_flip() +
  geom_hline(yintercept = 0.2, lty = "longdash", color = "grey40") +
  geom_hline(yintercept = 0.5, lty = "longdash", color = "grey40") +
  geom_hline(yintercept = 0.8, lty = "longdash", color = "grey40") +
  geom_point(size=6, shape=21, colour="white", stroke = 2) +
  scale_fill_manual(values=barCOLS) +
  scale_color_manual(values=dotCOLS) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.5, 0.8, 1, 1.5), labels = c(0, 0.1, 0.2, 0.5, 0.8, 1, 1.5), expand = c(0, 0.05)) +
  theme_bw() +
  guides(fill = "none", color = "none") +
  labs(x = "", y = bquote(paste("Effect size benchmark"~"(", italic(d), ~ "family", ")")) ) +
  
  theme(axis.title = element_text(size = 18),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 16),
        strip.text = element_text(size = 18, color = "black"),
        plot.margin=unit(c(0,0.8,0.1,-0.5), 'cm')) +
  ggforce::facet_col(
    facets = ~Field,
    scales = "free_y",
    space = "free",
    strip.position = "top")

png(filename = "fig 2.png", width = 12, height = 12, units = "in", type = "windows", res = 400)
p + 
dev.off() 

cowplot::plot_grid(p, labels = c(' '), label_size = 16, nrow = 4, ncol = 1)

# plot_layout(tag_level = 'new') +  plot_annotation(tag_levels = list(c(''))) & theme(plot.tag = element_text(size = 16, face = "bold"))  
```


# Figure 3

https://github.com/jorvlan/raincloudplots

```{r}
# economic
df_1x1 <- data_1x1(
  array_1 = df_eco$folded_mu_adj,
  array_2 = df_eco$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p1 <- raincloud_1x1_repmes(
  data = df_1x1, # BottleRocket2
  colors = c("#009E73","#CC79A7"), # brewer.pal(n = 8, name = "Dark2")[1:2], #wes_palette("Rushmore1", 4, type = "discrete")[c(4,3,4,3)],
  fills = c("#009E73","#CC79A7"), # wes_palette("Rushmore1", 4, type = "discrete")[c(4,3,4,3)], # https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes") 
                   #limits=c(0, 100)
                   ) +
  labs(title = "Economics", x = " ", y = "Effect size") + 
  #annotate(geom = "text", x= 1, y = -1, label = "Publication bias") +
  #annotate(geom = "text", x= 4, y = -1, label = "No publication bias") +
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# environment
df_1x1 <- data_1x1(
  array_1 = df_env$folded_mu_adj,
  array_2 = df_env$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p2 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Environment", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# medicine
df_1x1 <- data_1x1(
  array_1 = df_med$folded_mu_adj,
  array_2 = df_med$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p3 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Medicine", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 


# medicine
df_1x1 <- data_1x1(
  array_1 = df_psy$folded_mu_adj,
  array_2 = df_psy$blup,
  jit_distance = .2, # 0.09
  jit_seed = 321)


p4 <- raincloud_1x1_repmes(
  data = df_1x1, 
  colors = c("#009E73","#CC79A7"), 
  fills = c("#009E73","#CC79A7"), 
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .5,
  align_clouds = FALSE) +

scale_x_continuous(breaks=c(1, 2), 
                   labels=c("Adjusted and folded", "Empirical Bayes")
                   ) +
  labs(title = "Psychology", x = " ", y = "Effect size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        plot.title = element_text(size = 18),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

png(filename = "fig 3.png", width = 6, height = 15, units = "in", type = "windows", res = 600)
cowplot::plot_grid(p1, p2, p4, p4, labels = c('A', 'B', 'C', 'D'), label_size = 16, nrow = 4, ncol = 1)
dev.off()

```

# Figure 4

https://rpsychologist.com/cohen-d-proportion-overlap

```{r}
# medicine
## small effect
ES <- quantile(df_med$folded_mu_adj, probs = 0.25)  
mean1 <- ES*1 + 1
x <- seq(1 - 3*1, mean1 + 3*1, .01)
y1 <- dnorm(x, 1, 1)
df1 <- data.frame("x" = x, "y" = y1)
y2 <- dnorm(x, mean1, 1)
df2 <- data.frame("x" = x, "y" = y2)
y.poly <- pmin(y1,y2)
poly <- data.frame("x" = x, "y" = y.poly)

u3 <- 1 - pnorm(1, mean1,1)
u3 <- round(u3,3)

fig3b <- ggplot(df1, aes(x,y, color="Exp")) +
  geom_line() + 
  geom_line(data=df2, aes(color="Con")) +
  geom_polygon(aes(color=NULL), data=poly, fill="red", alpha=I(4/10),
               show.legend=FALSE) +
  geom_vline(xintercept = 1, linetype="dotted") + 
  geom_vline(xintercept = mean1, linetype="dotted") + 
  scale_color_manual("Group", 
                     values= c("Exp" = "black","Con" = "red")) +
  ylab(NULL) + xlab(NULL) +
  scale_fill_discrete(name="Group", 
                      breaks=c("Con", "Exp"),
                      labels=c("Control", "Treatment")) + 
  theme_bw() + 
  theme(legend.position="none",
        axis.title = element_text(size = 18),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 16)) 


## medium effect
ES <- quantile(df_med$folded_mu_adj, probs = 0.50)  
mean1 <- ES*1 + 1
x <- seq(1 - 3*1, mean1 + 3*1, .01)
y1 <- dnorm(x, 1, 1)
df1 <- data.frame("x" = x, "y" = y1)
y2 <- dnorm(x, mean1, 1)
df2 <- data.frame("x" = x, "y" = y2)
y.poly <- pmin(y1,y2)
poly <- data.frame("x" = x, "y" = y.poly)

u3 <- 1 - pnorm(1, mean1,1)
u3 <- round(u3,3)

fig3b <- ggplot(df1, aes(x,y, color="Exp")) +
  geom_line() + 
  geom_line(data=df2, aes(color="Con")) +
  geom_polygon(aes(color=NULL), data=poly, fill="red", alpha=I(4/10),
               show.legend=FALSE) +
  geom_vline(xintercept = 1, linetype="dotted") + 
  geom_vline(xintercept = mean1, linetype="dotted") + 
  scale_color_manual("Group", 
                     values= c("Exp" = "black","Con" = "red")) +
  ylab(NULL) + xlab(NULL) +
  scale_fill_discrete(name="Group", 
                      breaks=c("Con", "Exp"),
                      labels=c("Control", "Treatment")) + 
  theme_bw() + 
  theme(legend.position="none",
        axis.title = element_text(size = 18),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 16)) 


## large effect
ES <- quantile(df_med$folded_mu_adj, probs = 0.75)  
mean1 <- ES*1 + 1
x <- seq(1 - 3*1, mean1 + 3*1, .01)
y1 <- dnorm(x, 1, 1)
df1 <- data.frame("x" = x, "y" = y1)
y2 <- dnorm(x, mean1, 1)
df2 <- data.frame("x" = x, "y" = y2)
y.poly <- pmin(y1,y2)
poly <- data.frame("x" = x, "y" = y.poly)

u3 <- 1 - pnorm(1, mean1,1)
u3 <- round(u3,3)

fig3b <- ggplot(df1, aes(x,y, color="Exp")) +
  geom_line() + 
  geom_line(data=df2, aes(color="Con")) +
  geom_polygon(aes(color=NULL), data=poly, fill="red", alpha=I(4/10),
               show.legend=FALSE) +
  geom_vline(xintercept = 1, linetype="dotted") + 
  geom_vline(xintercept = mean1, linetype="dotted") + 
  scale_color_manual("Group", 
                     values= c("Exp" = "black","Con" = "red")) +
  ylab(NULL) + xlab(NULL) +
  scale_fill_discrete(name="Group", 
                      breaks=c("Con", "Exp"),
                      labels=c("Control", "Treatment")) + 
  theme_bw() + 
  theme(legend.position="none",
        axis.title = element_text(size = 18),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 16)) 

fig3 <- plot_grid(fig3a, fig3b, fig3c, ncol = 1)
save_plot("fig2.pdf", fig3, base_height = 20, base_width = 8)
```


